spring.application.name=pruebaTecnica

spring.datasource.url=jdbc:postgresql://localhost:5432/pruebatecnica
spring.datasource.username=app_user
spring.datasource.password=B4nregio2803$
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080


# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false
logging.level.org.flywaydb=DEBUG

#========================
# JWT Configuration
#========================
# Clave secreta para firmar los tokens (m�nimo 256 bits para HS256).
# En producci�n NUNCA pongas esto aqu�, usa variables de entorno.
jwt.secret=tx6qmTWoJBzuZHec56LhW02qLvjsY9q3YGkGtKoOHn18k1jc3HEOlThjVylWSJ5oLKshiK4682FUMqAEurt7WT
# Tiempo de expiraci�n en milisegundos (86400000 = 24 horas)
jwt.expiration=86400000



#========================
# DATASOURCE H2
#========================
#spring.datasource.url=jdbc:h2:mem:pruebaTecnicaDB;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa


#========================
# JPA / HIBERNATE
#========================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#========================
# para que h2 se comporte como mysql para pruebas
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#========================
# H2 Console
#========================
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#========================
# SWAGGER / OPENAPI
#========================
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
#springdoc.swagger-ui.tryItOutEnabled=true

